//! Data for the feature-matrix conformance suite.
//!
//! Each row pairs a syntax with the support level regexr claims for it and the
//! probes that decide it. The runner lives in `mod.rs`.

use super::{Feature, Group, Probe, Support};

pub const GROUPS: &[Group] = &[
    Group {
        name: "General",
        features: GENERAL,
    },
    Group {
        name: "Quantifiers",
        features: QUANTIFIERS,
    },
    Group {
        name: "Escapes",
        features: ESCAPES,
    },
    Group {
        name: "Escapes inside sets",
        features: ESCAPES_IN_SETS,
    },
    Group {
        name: "Classes",
        features: CLASSES,
    },
    Group {
        name: "Operators inside sets",
        features: SET_OPERATORS,
    },
    Group {
        name: "Anchors",
        features: ANCHORS,
    },
    Group {
        name: "Named groups and backreferences",
        features: NAMED_GROUPS,
    },
    Group {
        name: "Grouping and lookaround",
        features: GROUPING,
    },
    Group {
        name: "Recursive patterns",
        features: RECURSIVE,
    },
    Group {
        name: "Conditionals",
        features: CONDITIONALS,
    },
    Group {
        name: "Miscellaneous",
        features: MISCELLANEOUS,
    },
];

const GENERAL: &[Feature] = &[
    Feature {
        syntax: "(…)",
        desc: "capturing group around a subexpression",
        support: Support::Yes,
        covered_by: Some("features::syntax"),
        probes: &[],
    },
    Feature {
        syntax: "[…]",
        desc: "character class matching any one listed character",
        support: Support::Yes,
        covered_by: Some("features::syntax"),
        probes: &[],
    },
    Feature {
        syntax: "|",
        desc: "alternation between two branches",
        support: Support::Yes,
        covered_by: Some("features::syntax"),
        probes: &[],
    },
    Feature {
        syntax: "#comment",
        desc: "extended-mode line comment running from `#` to end of line",
        support: Support::Yes,
        covered_by: Some("features::extended_mode"),
        probes: &[],
    },
    Feature {
        syntax: "(?#comment)",
        desc: "inline comment group, ignored and non-consuming",
        support: Support::Yes,
        covered_by: Some("features::syntax"),
        probes: &[],
    },
    Feature {
        syntax: "[#comment]",
        desc: "`#` inside a bracket expression, literal even under extended mode",
        support: Support::Yes,
        covered_by: None,
        probes: &[Probe {
            pattern: r"[#ab]",
            matches: Some("#"),
            rejects: Some("c"),
            expect: Some("#"),
            icase: false,
            xmode: true,
        }],
    },
    Feature {
        syntax: "(?flags)",
        desc: "inline flag setting that applies from that point onward",
        support: Support::Yes,
        covered_by: Some("features::inline_flags"),
        probes: &[],
    },
    Feature {
        syntax: "(?flags:…)",
        desc: "inline flags scoped to a non-capturing group",
        support: Support::Yes,
        covered_by: Some("features::inline_flags"),
        probes: &[],
    },
    Feature {
        syntax: "(?^flags)",
        desc: "inline flags that first reset to defaults, then apply the given set",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: r"(?i)cat(?^)DOG",
            matches: Some("CATDOG"),
            rejects: Some("catdog"),
            expect: Some("CATDOG"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: "(?^flags:…)",
        desc: "reset-then-set inline flags scoped to a non-capturing group",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: r"(?i)a(?^:b)",
            matches: Some("Ab"),
            rejects: Some("AB"),
            expect: Some("Ab"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: "(?x)",
        desc: "extended mode: unescaped whitespace outside classes is ignored",
        support: Support::Yes,
        covered_by: Some("features::extended_mode"),
        probes: &[],
    },
    Feature {
        syntax: "(?xx)",
        desc: "extended mode that also ignores whitespace inside bracket expressions",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: "(?xx)[a b]",
            matches: Some("b"),
            rejects: Some(" "),
            expect: Some("b"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: r"\Q…\E",
        desc: "literal quoting: metacharacters between the delimiters are treated literally",
        support: Support::Yes,
        covered_by: Some("features::quoting"),
        probes: &[],
    },
    Feature {
        syntax: r"[\Q…\E]",
        desc: "literal quoting inside a bracket expression, each quoted character a member",
        support: Support::Yes,
        covered_by: Some("features::quoting"),
        probes: &[],
    },
    Feature {
        syntax: r"[\q{…}]",
        desc: "bracketed string-list set: each braced alternative is a whole-string member",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: r"[\q{cat|dog}]",
            matches: Some("cat"),
            rejects: Some("cow"),
            expect: Some("cat"),
            icase: false,
            xmode: false,
        }],
    },
];

const QUANTIFIERS: &[Feature] = &[
    Feature {
        syntax: "*",
        desc: "zero or more repetitions, greedy",
        support: Support::Yes,
        covered_by: Some("features::syntax"),
        probes: &[],
    },
    Feature {
        syntax: "+",
        desc: "one or more repetitions, greedy",
        support: Support::Yes,
        covered_by: Some("features::syntax"),
        probes: &[],
    },
    Feature {
        syntax: "?",
        desc: "zero or one repetition, greedy",
        support: Support::Yes,
        covered_by: Some("features::syntax"),
        probes: &[],
    },
    Feature {
        syntax: "{n,m}",
        desc: "bounded repetition between n and m times, greedy",
        support: Support::Yes,
        covered_by: Some("features::syntax"),
        probes: &[],
    },
    Feature {
        syntax: "{,m}",
        desc: "bounded repetition with an implied lower bound of zero",
        support: Support::Yes,
        covered_by: None,
        probes: &[Probe {
            pattern: r"a{,3}",
            matches: Some("aaaa"),
            rejects: None,
            expect: Some("aaa"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: "*?, +?, ??, {}?",
        desc: "lazy (non-greedy) suffix on a quantifier, matching as little as possible",
        support: Support::Yes,
        covered_by: None,
        probes: &[
            Probe {
                pattern: r"a.*?b",
                matches: Some("axxbxxb"),
                rejects: None,
                expect: Some("axxb"),
                icase: false,
                xmode: false,
            },
            Probe {
                pattern: r"ab??",
                matches: Some("ab"),
                rejects: None,
                expect: Some("a"),
                icase: false,
                xmode: false,
            },
        ],
    },
    // Deliberately unsupported: possessive quantifiers bound backtracking, and
    // regexr's engines do not backtrack. Rejected with a diagnostic naming the
    // construct rather than silently accepted as plain greedy, which is only
    // usually equivalent.
    Feature {
        syntax: "*+, ++, ?+, {}+",
        desc: "possessive suffix on a quantifier, forbidding backtracking into it",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: r"a*+a",
            matches: None,
            rejects: Some("aaa"),
            expect: None,
            icase: false,
            xmode: false,
        }],
    },
];

const ESCAPES: &[Feature] = &[
    Feature {
        syntax: r"\a",
        desc: "bell character escape (0x07)",
        support: Support::Yes,
        covered_by: Some("features::escape_sequences"),
        probes: &[],
    },
    Feature {
        syntax: r"\e",
        desc: "escape character (0x1B)",
        support: Support::Yes,
        covered_by: Some("features::escape_sequences"),
        probes: &[],
    },
    Feature {
        syntax: r"\f",
        desc: "form feed character escape (0x0C)",
        support: Support::Yes,
        covered_by: Some("features::escape_sequences"),
        probes: &[],
    },
    Feature {
        syntax: r"\n",
        desc: "line feed character escape",
        support: Support::Yes,
        covered_by: Some("features::escape_sequences"),
        probes: &[],
    },
    Feature {
        syntax: r"\r",
        desc: "carriage return character escape",
        support: Support::Yes,
        covered_by: Some("features::escape_sequences"),
        probes: &[],
    },
    Feature {
        syntax: r"\t",
        desc: "horizontal tab character escape",
        support: Support::Yes,
        covered_by: Some("features::escape_sequences"),
        probes: &[],
    },
    Feature {
        syntax: r"\v",
        desc: "vertical tab character escape (0x0B), outside a bracket expression",
        support: Support::Yes,
        covered_by: Some("features::escape_sequences"),
        probes: &[],
    },
    Feature {
        syntax: r"\1..\7",
        desc: "single-digit octal escape, used when the digit cannot be a backreference",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: r"\1",
            matches: Some("\u{1}"),
            rejects: Some("1"),
            expect: Some("\u{1}"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: r"\nn, \nnn",
        desc: "two- or three-digit octal escape",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: r"\101",
            matches: Some("A"),
            rejects: Some("101"),
            expect: Some("A"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: r"\0nnn",
        desc: "octal escape explicitly led by a zero digit",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: r"\0101",
            matches: Some("\u{8}1"),
            rejects: Some("0101"),
            expect: Some("\u{8}1"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: r"\o{nn…}",
        desc: "braced octal escape",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: r"\o{101}",
            matches: Some("A"),
            rejects: Some("101"),
            expect: Some("A"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: r"\xXX",
        desc: "two-digit hexadecimal escape",
        support: Support::Yes,
        covered_by: None,
        probes: &[Probe {
            pattern: r"\x41",
            matches: Some("A"),
            rejects: Some("41"),
            expect: Some("A"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: r"\x{XX…}",
        desc: "braced hexadecimal escape of variable length",
        support: Support::Yes,
        covered_by: Some("features::escape_sequences"),
        probes: &[],
    },
    Feature {
        syntax: r"\uXXXX",
        desc: "four-digit hexadecimal escape (ECMAScript style)",
        support: Support::Yes,
        covered_by: None,
        probes: &[Probe {
            pattern: "\\u0041",
            matches: Some("A"),
            rejects: Some("0041"),
            expect: Some("A"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: r"\UXXXXXXXX",
        desc: "eight-digit hexadecimal escape (Python style)",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: r"\U0001F600",
            matches: Some("\u{1f600}"),
            rejects: Some("0001F600"),
            expect: Some("\u{1f600}"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: r"\u{XX…}",
        desc: "braced hexadecimal escape of variable length (ES2015 style)",
        support: Support::Yes,
        covered_by: None,
        probes: &[Probe {
            pattern: r"\u{1F600}",
            matches: Some("\u{1f600}"),
            rejects: Some("1F600"),
            expect: Some("\u{1f600}"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: r"\U{XX…}",
        desc: "braced hexadecimal escape, alternate uppercase spelling",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: r"\U{0001F600}",
            matches: Some("\u{1f600}"),
            rejects: Some("1F600"),
            expect: Some("\u{1f600}"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: r"\cC",
        desc: "control-character escape, letter XORed against 0x40",
        support: Support::Yes,
        covered_by: Some("features::escape_sequences"),
        probes: &[],
    },
    Feature {
        syntax: r"\CC",
        desc: "control-character escape, alternate uppercase-C spelling",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: r"\CJ",
            matches: Some("\n"),
            rejects: Some("J"),
            expect: Some("\n"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: r"\C-C",
        desc: "control-character escape, hyphenated Oniguruma spelling",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: r"\C-J",
            matches: Some("\n"),
            rejects: Some("J"),
            expect: Some("\n"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: r"\N{…}",
        desc: "named Unicode character escape",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: r"\N{LATIN SMALL LETTER A}",
            matches: Some("a"),
            rejects: Some("b"),
            expect: Some("a"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: r"\any",
        desc: "generic escape rule: an escaped ASCII punctuation character stands for itself",
        support: Support::Yes,
        covered_by: None,
        probes: &[Probe {
            pattern: r"\-",
            matches: Some("-"),
            rejects: Some("x"),
            expect: Some("-"),
            icase: false,
            xmode: false,
        }],
    },
];

const ESCAPES_IN_SETS: &[Feature] = &[
    Feature {
        syntax: r"[\a]",
        desc: "bell character escape inside a bracket expression",
        support: Support::Yes,
        covered_by: Some("features::escape_sequences"),
        probes: &[],
    },
    Feature {
        syntax: r"[\b]",
        desc: "backspace character escape inside a bracket expression",
        support: Support::Yes,
        covered_by: Some("features::escape_sequences"),
        probes: &[],
    },
    Feature {
        syntax: r"[\e]",
        desc: "escape character escape inside a bracket expression",
        support: Support::Yes,
        covered_by: Some("features::escape_sequences"),
        probes: &[],
    },
    Feature {
        syntax: r"[\f]",
        desc: "form feed character escape inside a bracket expression",
        support: Support::Yes,
        covered_by: Some("features::escape_sequences"),
        probes: &[],
    },
    Feature {
        syntax: r"[\n]",
        desc: "line feed character escape inside a bracket expression",
        support: Support::Yes,
        covered_by: Some("features::escape_sequences"),
        probes: &[],
    },
    Feature {
        syntax: r"[\r]",
        desc: "carriage return character escape inside a bracket expression",
        support: Support::Yes,
        covered_by: Some("features::escape_sequences"),
        probes: &[],
    },
    Feature {
        syntax: r"[\t]",
        desc: "horizontal tab character escape inside a bracket expression",
        support: Support::Yes,
        covered_by: Some("features::escape_sequences"),
        probes: &[],
    },
    Feature {
        syntax: r"[\v]",
        desc: "vertical tab character escape inside a bracket expression",
        support: Support::Yes,
        covered_by: Some("features::escape_sequences"),
        probes: &[],
    },
    Feature {
        syntax: r"[\1..\7]",
        desc: "single-digit octal escape inside a bracket expression, unambiguous with backreferences",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: r"[\1]",
            matches: Some("\u{1}"),
            rejects: Some("1"),
            expect: Some("\u{1}"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: r"[\nn], [\nnn]",
        desc: "two- or three-digit octal escape inside a bracket expression",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: r"[\101]",
            matches: Some("A"),
            rejects: Some("101"),
            expect: Some("A"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: r"[\0nnn]",
        desc: "zero-led octal escape inside a bracket expression",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            // `1` is a class member either way, so the probe pins the octal
            // character instead — that member only exists if `\0nnn` is honoured.
            pattern: r"[\0101]",
            matches: Some("\u{8}"),
            rejects: Some("x"),
            expect: Some("\u{8}"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: r"[\o{nn…}]",
        desc: "braced octal escape inside a bracket expression",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: r"[\o{101}]",
            matches: Some("A"),
            rejects: Some("101"),
            expect: Some("A"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: r"[\xXX]",
        desc: "two-digit hexadecimal escape inside a bracket expression",
        support: Support::Yes,
        covered_by: None,
        probes: &[Probe {
            pattern: r"[\x41]",
            matches: Some("A"),
            rejects: Some("41"),
            expect: Some("A"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: r"[\x{XX…}]",
        desc: "braced hexadecimal escape inside a bracket expression",
        support: Support::Yes,
        covered_by: Some("features::escape_sequences"),
        probes: &[],
    },
    Feature {
        syntax: r"[\uXXXX]",
        desc: "four-digit hexadecimal escape inside a bracket expression",
        support: Support::Yes,
        covered_by: None,
        probes: &[Probe {
            pattern: "[\\u0041]",
            matches: Some("A"),
            rejects: Some("0041"),
            expect: Some("A"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: r"[\UXXXXXXXX]",
        desc: "eight-digit hexadecimal escape inside a bracket expression",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: r"[\U0001F600]",
            matches: Some("\u{1f600}"),
            rejects: Some("0001F600"),
            expect: Some("\u{1f600}"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: r"[\u{XX…}]",
        desc: "braced variable-length hexadecimal escape inside a bracket expression",
        support: Support::Yes,
        covered_by: None,
        probes: &[Probe {
            pattern: r"[\u{1F600}]",
            matches: Some("\u{1f600}"),
            rejects: Some("1F600"),
            expect: Some("\u{1f600}"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: r"[\U{XX…}]",
        desc: "braced hexadecimal escape, alternate uppercase spelling, inside a bracket expression",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: r"[\U{0001F600}]",
            matches: Some("\u{1f600}"),
            rejects: Some("1F600"),
            expect: Some("\u{1f600}"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: r"[\cC]",
        desc: "control-character escape inside a bracket expression",
        support: Support::Yes,
        covered_by: Some("features::escape_sequences"),
        probes: &[],
    },
    Feature {
        syntax: r"[\CC]",
        desc: "control-character escape, alternate uppercase-C spelling, inside a bracket expression",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: r"[\CJ]",
            matches: Some("\n"),
            rejects: Some("J"),
            expect: Some("\n"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: r"[\C-C]",
        desc: "control-character escape, hyphenated spelling, inside a bracket expression",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: r"[\C-J]",
            matches: Some("\n"),
            rejects: Some("J"),
            expect: Some("\n"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: r"[\N{…}]",
        desc: "named Unicode character escape inside a bracket expression",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: r"[\N{LATIN SMALL LETTER A}]",
            matches: Some("a"),
            rejects: Some("b"),
            expect: Some("a"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: r"[\any]",
        desc: "generic escape rule inside a bracket expression: an escaped ASCII punctuation character stands for itself",
        support: Support::Yes,
        covered_by: None,
        probes: &[Probe {
            pattern: r"[\-]",
            matches: Some("-"),
            rejects: Some("x"),
            expect: Some("-"),
            icase: false,
            xmode: false,
        }],
    },
];

const CLASSES: &[Feature] = &[
    Feature {
        syntax: ".",
        desc: "any character except the line terminator",
        support: Support::Yes,
        covered_by: None,
        probes: &[
            Probe {
                pattern: r"a.c",
                matches: Some("abc"),
                rejects: Some("a\nc"),
                expect: Some("abc"),
                icase: false,
                xmode: false,
            },
            // A single `.` must span a whole multi-byte character, not one byte
            // of it.
            Probe {
                pattern: r"a.c",
                matches: Some("aéc"),
                rejects: None,
                expect: Some("aéc"),
                icase: false,
                xmode: false,
            },
        ],
    },
    Feature {
        syntax: r"\d, \D",
        desc: "decimal digit class and its negation",
        support: Support::Yes,
        covered_by: None,
        probes: &[
            Probe {
                pattern: r"\d+",
                matches: Some("abc123"),
                rejects: Some("abc"),
                expect: Some("123"),
                icase: false,
                xmode: false,
            },
            Probe {
                pattern: r"\D+",
                matches: Some("123abc456"),
                rejects: None,
                expect: Some("abc"),
                icase: false,
                xmode: false,
            },
        ],
    },
    Feature {
        syntax: r"\h, \H",
        desc: "horizontal whitespace class and its negation",
        support: Support::Yes,
        covered_by: Some("features::escape_sequences"),
        probes: &[],
    },
    Feature {
        syntax: r"\N",
        desc: "any character except the line feed (bare, unbraced)",
        support: Support::Yes,
        covered_by: Some("features::escape_sequences"),
        probes: &[],
    },
    Feature {
        syntax: r"\R",
        desc: "any recognized Unicode line-break sequence, matched as a single unit",
        support: Support::Yes,
        covered_by: Some("features::escape_sequences"),
        probes: &[],
    },
    Feature {
        syntax: r"\s, \S",
        desc: "whitespace class and its negation",
        support: Support::Yes,
        covered_by: Some("features::syntax"),
        probes: &[],
    },
    Feature {
        syntax: r"\v, \V",
        desc: "vertical whitespace class and its negation",
        support: Support::No,
        covered_by: None,
        probes: &[
            Probe {
                pattern: r"\v+",
                matches: Some("a\r\nb"),
                rejects: Some("a b"),
                expect: Some("\r\n"),
                icase: false,
                xmode: false,
            },
            Probe {
                pattern: r"\V+",
                matches: Some("ab\ncd"),
                rejects: None,
                expect: Some("ab"),
                icase: false,
                xmode: false,
            },
        ],
    },
    Feature {
        syntax: r"\w, \W",
        desc: "word-character class and its negation",
        support: Support::Yes,
        covered_by: Some("features::syntax"),
        probes: &[],
    },
    Feature {
        syntax: r"\X",
        desc: "one extended grapheme cluster",
        support: Support::Yes,
        covered_by: Some("features::grapheme_cluster"),
        probes: &[],
    },
    Feature {
        syntax: r"\pX, \PX",
        desc: "single-letter Unicode general-category shorthand and its negation",
        support: Support::Yes,
        covered_by: None,
        probes: &[
            Probe {
                pattern: r"\pL+",
                matches: Some("abc123"),
                rejects: None,
                expect: Some("abc"),
                icase: false,
                xmode: false,
            },
            Probe {
                pattern: r"\PL+",
                matches: Some("123abc"),
                rejects: None,
                expect: Some("123"),
                icase: false,
                xmode: false,
            },
        ],
    },
    Feature {
        syntax: r"\p{…}, \P{…}",
        desc: "braced Unicode property class and its negation",
        support: Support::Yes,
        covered_by: Some("features::syntax"),
        probes: &[],
    },
    Feature {
        syntax: r"[\d], [\D]",
        desc: "decimal digit class and its negation, inside a bracket expression",
        support: Support::Yes,
        covered_by: None,
        probes: &[
            Probe {
                pattern: r"[\d]+",
                matches: Some("a1b2"),
                rejects: None,
                expect: Some("1"),
                icase: false,
                xmode: false,
            },
            Probe {
                pattern: r"[\D]+",
                matches: Some("1ab2"),
                rejects: None,
                expect: Some("ab"),
                icase: false,
                xmode: false,
            },
        ],
    },
    Feature {
        syntax: r"[\h], [\H]",
        desc: "horizontal whitespace class and its negation, inside a bracket expression",
        support: Support::Yes,
        covered_by: Some("features::escape_sequences"),
        probes: &[],
    },
    Feature {
        syntax: r"[\R]",
        desc: "line-break escape written inside a bracket expression, where its multi-character meaning cannot apply",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: r"[\R]",
            matches: Some("R"),
            rejects: Some("\n"),
            expect: Some("R"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: r"[\s], [\S]",
        desc: "whitespace class and its negation, inside a bracket expression",
        support: Support::Yes,
        covered_by: None,
        probes: &[
            Probe {
                pattern: r"[\s]+",
                matches: Some("a b"),
                rejects: None,
                expect: Some(" "),
                icase: false,
                xmode: false,
            },
            Probe {
                pattern: r"[\S]+",
                matches: Some(" ab "),
                rejects: None,
                expect: Some("ab"),
                icase: false,
                xmode: false,
            },
        ],
    },
    Feature {
        syntax: r"[\v], [\V]",
        desc: "vertical whitespace class and its negation, inside a bracket expression",
        support: Support::No,
        covered_by: None,
        probes: &[
            Probe {
                pattern: r"[\v]+",
                matches: Some("a\nb"),
                rejects: None,
                expect: Some("\n"),
                icase: false,
                xmode: false,
            },
            Probe {
                pattern: r"[\V]+",
                matches: Some("\nab\n"),
                rejects: None,
                expect: Some("ab"),
                icase: false,
                xmode: false,
            },
        ],
    },
    Feature {
        syntax: r"[\w], [\W]",
        desc: "word-character class and its negation, inside a bracket expression",
        support: Support::Yes,
        covered_by: None,
        probes: &[
            Probe {
                pattern: r"[\w]+",
                matches: Some("hi!"),
                rejects: None,
                expect: Some("hi"),
                icase: false,
                xmode: false,
            },
            Probe {
                pattern: r"[\W]+",
                matches: Some("!!hi"),
                rejects: None,
                expect: Some("!!"),
                icase: false,
                xmode: false,
            },
        ],
    },
    Feature {
        syntax: r"[\X]",
        desc: "grapheme-cluster escape written inside a bracket expression, where its multi-character meaning cannot apply",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: r"[\X]",
            matches: Some("X"),
            rejects: Some("e\u{301}"),
            expect: Some("X"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: r"[\pX], [\PX]",
        desc: "single-letter Unicode property shorthand and its negation, inside a bracket expression",
        support: Support::Yes,
        covered_by: None,
        probes: &[
            Probe {
                pattern: r"[\pL]+",
                matches: Some("aB1"),
                rejects: None,
                expect: Some("aB"),
                icase: false,
                xmode: false,
            },
            Probe {
                pattern: r"[\PL]+",
                matches: Some("1aB"),
                rejects: None,
                expect: Some("1"),
                icase: false,
                xmode: false,
            },
        ],
    },
    Feature {
        syntax: r"[\p{…}], [\P{…}]",
        desc: "braced Unicode property class and its negation, inside a bracket expression",
        support: Support::Yes,
        covered_by: None,
        probes: &[
            Probe {
                pattern: r"[\p{Greek}]+",
                matches: Some("aΑb"),
                rejects: None,
                expect: Some("Α"),
                icase: false,
                xmode: false,
            },
            Probe {
                pattern: r"[\P{Greek}]+",
                matches: Some("Αab"),
                rejects: None,
                expect: Some("ab"),
                icase: false,
                xmode: false,
            },
        ],
    },
    Feature {
        syntax: "[[:class:]]",
        desc: "POSIX class name inside a bracket expression",
        support: Support::Yes,
        covered_by: Some("features::posix_class"),
        probes: &[],
    },
];

const SET_OPERATORS: &[Feature] = &[
    Feature {
        syntax: "[[…] op […]]",
        desc: "nested bracket-class operation, whose operand is itself a full bracket expression",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: "[a-z-[aeiou]]+",
            matches: Some("sky"),
            rejects: Some("aeiou"),
            expect: Some("sky"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: "[…] & […]",
        desc: "intersection of two adjacent bracket expressions",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: "[a-z]&[aeiou]",
            matches: Some("cat"),
            rejects: Some("xyz"),
            expect: Some("a"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: "[…] + […]",
        desc: "union of two adjacent bracket expressions via `+`",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: "[ab]+[cd]",
            matches: Some("b"),
            rejects: Some("x"),
            expect: Some("b"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: "[…] | […]",
        desc: "union of two adjacent bracket expressions via `|`",
        support: Support::Yes,
        covered_by: None,
        probes: &[Probe {
            pattern: "[[ab]|[cd]]",
            matches: Some("c"),
            rejects: Some("x"),
            expect: Some("c"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: "[…] - […]",
        desc: "difference of two adjacent bracket expressions",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: "[a-z]-[aeiou]",
            matches: Some("b"),
            rejects: Some("a"),
            expect: Some("b"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: "[…] ^ […]",
        desc: "symmetric difference of two adjacent bracket expressions",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: "[abc]^[bcd]",
            matches: Some("a"),
            rejects: Some("b"),
            expect: Some("a"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: "![…]",
        desc: "bang-prefixed negation of a bracket expression, an alternative to `^`",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: "![abc]",
            matches: Some("xyz"),
            rejects: Some("abc"),
            expect: Some("x"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: "[…] && […]",
        desc: "intersection of a bracket expression with a nested one, double-ampersand spelling",
        support: Support::Yes,
        covered_by: Some("features::class_set_ops"),
        probes: &[],
    },
    Feature {
        syntax: "[…] || […]",
        desc: "union of two adjacent bracket expressions, double-pipe spelling",
        support: Support::Yes,
        covered_by: None,
        probes: &[Probe {
            pattern: "[[ab]||[cd]]",
            matches: Some("c"),
            rejects: Some("x"),
            expect: Some("c"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: "[…] -- […]",
        desc: "difference of a bracket expression and a nested one, double-dash spelling",
        support: Support::Yes,
        covered_by: Some("features::class_set_ops"),
        probes: &[],
    },
    Feature {
        syntax: "[…] ~~ […]",
        desc:
            "symmetric difference of a bracket expression and a nested one, double-tilde spelling",
        support: Support::Yes,
        covered_by: Some("features::class_set_ops"),
        probes: &[],
    },
];

const ANCHORS: &[Feature] = &[
    Feature {
        syntax: "^",
        desc: "start-of-line (or string) anchor",
        support: Support::Yes,
        covered_by: Some("features::syntax"),
        probes: &[],
    },
    Feature {
        syntax: "$",
        desc: "end-of-line (or string) anchor",
        support: Support::Yes,
        covered_by: Some("features::syntax"),
        probes: &[],
    },
    Feature {
        syntax: r"\A",
        desc: "absolute start of the subject string",
        support: Support::Yes,
        covered_by: None,
        probes: &[Probe {
            pattern: r"\Aabc",
            matches: Some("abcdef"),
            rejects: Some("xabc"),
            expect: Some("abc"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: r"\Z",
        desc: "end of the subject string, allowing one trailing line terminator",
        support: Support::Yes,
        covered_by: None,
        probes: &[Probe {
            pattern: "abc\\Z",
            matches: Some("abc\n"),
            rejects: Some("abcx"),
            expect: Some("abc"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: r"\z",
        desc: "absolute end of the subject string, no trailing line terminator allowed",
        support: Support::Yes,
        covered_by: None,
        probes: &[Probe {
            pattern: r"abc\z",
            matches: Some("xabc"),
            rejects: Some("abc\n"),
            expect: Some("abc"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: r"\G",
        desc: "anchor at the position where the previous match ended",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: r"\Gab",
            matches: Some("abab"),
            rejects: Some("xab"),
            expect: Some("ab"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: r"\b, \B",
        desc: "word boundary and non-boundary assertions",
        support: Support::Yes,
        covered_by: Some("features::word_boundary"),
        probes: &[],
    },
    Feature {
        syntax: r"\b{g}",
        desc: "grapheme-cluster boundary assertion",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: "e\u{301}\\b{g}",
            matches: Some("e\u{301}b"),
            rejects: None,
            expect: Some("e\u{301}"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: r"\b{…}, \B{…}",
        desc: "generalized boundary assertion taking a boundary-type argument",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: r"\b{wb}cat\b{wb}",
            matches: Some("a cat sat"),
            rejects: Some("concatenate"),
            expect: Some("cat"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: r"\K",
        desc: "resets the reported match start, excluding everything matched so far",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: r"foo\Kbar",
            matches: Some("foobar"),
            rejects: Some("bar"),
            expect: Some("bar"),
            icase: false,
            xmode: false,
        }],
    },
];

const NAMED_GROUPS: &[Feature] = &[
    Feature {
        syntax: "(?'name'…)",
        desc: "named capturing group, quote-delimited",
        support: Support::Yes,
        covered_by: Some("features::named_capture"),
        probes: &[],
    },
    Feature {
        syntax: "(?<name>…)",
        desc: "named capturing group, angle-bracket delimited",
        support: Support::Yes,
        covered_by: Some("features::named_capture"),
        probes: &[],
    },
    Feature {
        syntax: "(?P<name>…)",
        desc: "named capturing group, Python-style",
        support: Support::Yes,
        covered_by: Some("features::named_capture"),
        probes: &[],
    },
    Feature {
        syntax: "Duplicate names",
        desc: "the same capture-group name reused across alternation branches",
        support: Support::Yes,
        covered_by: None,
        probes: &[Probe {
            pattern: "(?<n>cat)|(?<n>dog)",
            matches: Some("a dog ran"),
            rejects: Some("a fish"),
            expect: Some("dog"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: r"\1, \2, …, \9",
        desc: "numbered backreference to an earlier capturing group",
        support: Support::Yes,
        covered_by: Some("features::backreference"),
        probes: &[],
    },
    Feature {
        syntax: r"\nnn",
        desc: "multi-digit backreference, valid when that many capturing groups precede it",
        support: Support::Yes,
        covered_by: None,
        probes: &[Probe {
            pattern: r"(a)(b)(c)(d)(e)(f)(g)(h)(i)(j)\10",
            matches: Some("abcdefghijj"),
            rejects: Some("abcdefghij"),
            expect: Some("abcdefghijj"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: r"\k'name'",
        desc: "named backreference, quote-delimited",
        support: Support::Yes,
        covered_by: Some("features::backreference"),
        probes: &[],
    },
    Feature {
        syntax: r"\k<name>",
        desc: "named backreference, angle-bracket delimited",
        support: Support::Yes,
        covered_by: Some("features::backreference"),
        probes: &[],
    },
    Feature {
        syntax: r"\k{name}",
        desc: "named backreference, brace-delimited",
        support: Support::Yes,
        covered_by: Some("features::backreference"),
        probes: &[],
    },
    Feature {
        syntax: r"\kn",
        desc: "numbered backreference spelled with a `\\k` prefix",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: r"(cat) \k1",
            matches: Some("cat cat"),
            rejects: Some("cat dog"),
            expect: Some("cat cat"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: r"\k-n",
        desc: "relative-index backreference spelled with a `\\k` prefix",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: r"(cat) \k-1",
            matches: Some("cat cat"),
            rejects: Some("cat dog"),
            expect: Some("cat cat"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: r"\g'…'",
        desc: "named subroutine call or backreference, quote-delimited",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: "(?<w>cat) \\g'w'",
            matches: Some("cat cat"),
            rejects: Some("cat dog"),
            expect: Some("cat cat"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: r"\g<…>",
        desc: "named subroutine call or backreference, angle-bracket delimited",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: r"(?<w>cat) \g<w>",
            matches: Some("cat cat"),
            rejects: Some("cat dog"),
            expect: Some("cat cat"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: r"\gn",
        desc: "numbered subroutine call or backreference",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: r"(cat) \g1",
            matches: Some("cat cat"),
            rejects: Some("cat dog"),
            expect: Some("cat cat"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: r"\g-n",
        desc: "relative-index numbered subroutine call or backreference",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: r"(cat) \g-1",
            matches: Some("cat cat"),
            rejects: Some("cat dog"),
            expect: Some("cat cat"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: r"\g{…}",
        desc: "brace-delimited subroutine call or backreference, by name or number",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: r"(?<w>cat) \g{w}",
            matches: Some("cat cat"),
            rejects: Some("cat dog"),
            expect: Some("cat cat"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: "(?P=name)",
        desc: "named backreference, Python-style",
        support: Support::Yes,
        covered_by: Some("features::backreference"),
        probes: &[],
    },
];

const GROUPING: &[Feature] = &[
    Feature {
        syntax: "(?:…)",
        desc: "non-capturing group",
        support: Support::Yes,
        covered_by: None,
        probes: &[Probe {
            pattern: "(?:ab)+c",
            matches: Some("ababc"),
            rejects: Some("abxc"),
            expect: Some("ababc"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: "(?=…)",
        desc: "positive lookahead",
        support: Support::Yes,
        covered_by: Some("features::lookaround"),
        probes: &[],
    },
    Feature {
        syntax: "(?!…)",
        desc: "negative lookahead",
        support: Support::Yes,
        covered_by: Some("features::lookaround"),
        probes: &[],
    },
    Feature {
        syntax: "(?<=…)",
        desc: "positive lookbehind",
        support: Support::Yes,
        covered_by: Some("features::lookaround"),
        probes: &[],
    },
    Feature {
        syntax: "(?<!…)",
        desc: "negative lookbehind",
        support: Support::Yes,
        covered_by: Some("features::lookaround"),
        probes: &[],
    },
    Feature {
        syntax: "(?=…(?=…))",
        desc: "a lookahead nested inside another lookahead",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: "foo(?=bar(?=baz))",
            matches: Some("foobarbaz"),
            rejects: Some("foobarqux"),
            expect: Some("foo"),
            icase: false,
            xmode: false,
        }],
    },
    // Deliberately unsupported, for the same reason as possessive quantifiers:
    // an atomic group only constrains a backtracking search. RE2 and the `regex`
    // crate omit it on the same grounds.
    Feature {
        syntax: "(?>…)",
        desc: "atomic group, no backtracking once matched",
        support: Support::No,
        covered_by: None,
        probes: &[
            Probe {
                pattern: "(?>ab)c",
                matches: Some("abc"),
                rejects: None,
                expect: Some("abc"),
                icase: false,
                xmode: false,
            },
            Probe {
                pattern: "(?>a*)a",
                matches: None,
                rejects: Some("aaa"),
                expect: None,
                icase: false,
                xmode: false,
            },
        ],
    },
    Feature {
        syntax: "(?|…)",
        desc: "branch-reset group, alternatives share the same capture-group numbers",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: "(?|(a)|(b))",
            matches: Some("b"),
            rejects: Some("c"),
            expect: Some("b"),
            icase: false,
            xmode: false,
        }],
    },
];

const RECURSIVE: &[Feature] = &[
    Feature {
        syntax: "(?n)",
        desc: "recursive call to a numbered capturing group",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: "(a(?1)?b)",
            matches: Some("aabb"),
            rejects: Some("baa"),
            expect: Some("aabb"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: "(?-n), (?+n)",
        desc: "recursive call to a capturing group, numbered relative to the current position",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: "(a(?-1)?b)",
            matches: Some("aabb"),
            rejects: Some("baa"),
            expect: Some("aabb"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: "(?R)",
        desc: "recursive call to the whole pattern",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: "a(?R)?b",
            matches: Some("aabb"),
            rejects: Some("baa"),
            expect: Some("aabb"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: "(?&name)",
        desc: "recursive call to a named capturing group",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: "(?<x>a(?&x)?b)",
            matches: Some("aabb"),
            rejects: Some("baa"),
            expect: Some("aabb"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: "(?P>name)",
        desc: "recursive call to a named capturing group, Python-style",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: "(?P<x>a(?P>x)?b)",
            matches: Some("aabb"),
            rejects: Some("baa"),
            expect: Some("aabb"),
            icase: false,
            xmode: false,
        }],
    },
];

const CONDITIONALS: &[Feature] = &[
    Feature {
        syntax: "(?(number)…|…)",
        desc: "conditional whose test is whether a numbered group participated",
        support: Support::No,
        covered_by: None,
        probes: &[
            Probe {
                pattern: "(a)?(?(1)b|c)",
                matches: Some("ab"),
                rejects: Some("xyz"),
                expect: Some("ab"),
                icase: false,
                xmode: false,
            },
            Probe {
                pattern: "(a)?(?(1)b|c)",
                matches: Some("c"),
                rejects: None,
                expect: Some("c"),
                icase: false,
                xmode: false,
            },
        ],
    },
    Feature {
        syntax: "(?(name)…|…)",
        desc: "conditional whose test is whether a named group participated",
        support: Support::No,
        covered_by: None,
        probes: &[
            Probe {
                pattern: "(?<a>x)?(?(a)y|z)",
                matches: Some("xy"),
                rejects: Some("w"),
                expect: Some("xy"),
                icase: false,
                xmode: false,
            },
            Probe {
                pattern: "(?<a>x)?(?(a)y|z)",
                matches: Some("z"),
                rejects: None,
                expect: Some("z"),
                icase: false,
                xmode: false,
            },
        ],
    },
    Feature {
        syntax: "(?(pattern)…|…)",
        desc: "conditional whose test is an inline lookaround assertion",
        support: Support::No,
        covered_by: None,
        probes: &[
            Probe {
                pattern: "(?(?=x)xy|z)",
                matches: Some("xy"),
                rejects: Some("w"),
                expect: Some("xy"),
                icase: false,
                xmode: false,
            },
            Probe {
                pattern: "(?(?=x)xy|z)",
                matches: Some("z"),
                rejects: None,
                expect: Some("z"),
                icase: false,
                xmode: false,
            },
        ],
    },
    Feature {
        syntax: "(?(xxx)…|…)",
        desc: "conditional with only a true branch and no false-branch alternative",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: "^(a)?(?(1)b)$",
            matches: Some("ab"),
            rejects: Some("xyz"),
            expect: Some("ab"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: "(?('name')…|…)",
        desc: "conditional testing a quote-delimited named group",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: "(?'a'x)?(?('a')y|z)",
            matches: Some("xy"),
            rejects: Some("w"),
            expect: Some("xy"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: "(?(<name>)…|…)",
        desc: "conditional testing an angle-bracket-delimited named group",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: "(?<a>x)?(?(<a>)y|z)",
            matches: Some("xy"),
            rejects: Some("w"),
            expect: Some("xy"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: "(?(R)…|…)",
        desc: "conditional true only while currently inside recursion",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: "a(?(R)b)?",
            matches: Some("a"),
            rejects: Some("z"),
            expect: Some("a"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: "(?(R&name)…|…)",
        desc: "conditional true only while inside recursion of a specific named group",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: "(?<x>a(?(R&x)b))",
            matches: Some("a"),
            rejects: Some("z"),
            expect: Some("a"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: "(?(DEFINE)…|…)",
        desc: "declares reusable named subpatterns without matching them directly",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: r"(?(DEFINE)(?<num>\d+))(?&num)",
            matches: Some("123abc"),
            rejects: Some("abc"),
            expect: Some("123"),
            icase: false,
            xmode: false,
        }],
    },
];

const MISCELLANEOUS: &[Feature] = &[
    Feature {
        syntax: "(*verb)",
        desc: "backtracking control verb, e.g. forcing immediate failure or success",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: "a(*FAIL)b",
            matches: None,
            rejects: Some("ab"),
            expect: None,
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: "(*…:…)",
        desc: "backtracking control verb carrying a name argument",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: "a(*MARK:m1)b",
            matches: Some("ab"),
            rejects: Some("ac"),
            expect: Some("ab"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: "(?)",
        desc: "empty inline-flags group carrying no flags, a no-op",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: "a(?)b",
            matches: Some("ab"),
            rejects: Some("ac"),
            expect: Some("ab"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: "[]",
        desc: "empty bracket expression",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: "a[]b",
            matches: None,
            rejects: Some("ab"),
            expect: None,
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: "[^]",
        desc: "negated empty bracket expression, the complement of nothing",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: "a[^]b",
            matches: Some("axb"),
            rejects: Some("ab"),
            expect: Some("axb"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: "Unicode \".\"",
        desc: "dot matching a full Unicode code point, including supplementary-plane characters",
        support: Support::Yes,
        covered_by: None,
        probes: &[Probe {
            pattern: r"a.b",
            matches: Some("a\u{1f600}b"),
            rejects: Some("a\nb"),
            expect: Some("a\u{1f600}b"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: r#"Unicode "\w""#,
        desc: "word-character class recognizing letters outside the ASCII range",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: r"\w+",
            matches: Some("café"),
            rejects: Some("!!!"),
            expect: Some("café"),
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: "[Unicode]",
        desc: "bracket expression containing literal non-ASCII characters and ranges",
        support: Support::Yes,
        covered_by: None,
        probes: &[
            Probe {
                pattern: "[α-ω]+",
                matches: Some("xβγy"),
                rejects: Some("xyz"),
                expect: Some("βγ"),
                icase: false,
                xmode: false,
            },
            // The class must still span a whole character once it sits between
            // literals rather than standing alone.
            Probe {
                pattern: "X[é]Y",
                matches: Some("XéY"),
                rejects: Some("XeY"),
                expect: Some("XéY"),
                icase: false,
                xmode: false,
            },
        ],
    },
    Feature {
        syntax: "Surrogates",
        desc:
            "an escape naming a lone UTF-16 surrogate code point, not a valid Unicode scalar value",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: r"\x{D800}",
            matches: None,
            rejects: Some("a"),
            expect: None,
            icase: false,
            xmode: false,
        }],
    },
    Feature {
        syntax: "é=É",
        desc: "case-insensitive folding of accented Latin letters",
        support: Support::Yes,
        covered_by: Some("features::case_insensitive"),
        probes: &[],
    },
    Feature {
        syntax: "Σσς",
        desc: "case-insensitive folding unifying all forms of Greek sigma",
        support: Support::Yes,
        covered_by: Some("features::case_insensitive"),
        probes: &[],
    },
    Feature {
        syntax: "ß=SS",
        desc: "full case folding mapping German sharp s to \"ss\"",
        support: Support::No,
        covered_by: None,
        probes: &[Probe {
            pattern: "stra\u{df}e",
            matches: Some("STRASSE"),
            rejects: Some("strase"),
            expect: Some("STRASSE"),
            icase: true,
            xmode: false,
        }],
    },
];
