#!/usr/bin/env python3
"""
Derive the Indic_Conjunct_Break table from the UCD.

`ucd-generate` has no command for this enumerated property, but UAX #29 rule
GB9c needs it to keep Indic conjunct clusters (consonant + virama + consonant)
in one grapheme cluster. The property is published in DerivedCoreProperties.txt
as `InCB; <value>` lines.

Emits `indic_conjunct_break.rs` in the same shape as ucd-generate's output so
`generate_unicode.py` can consume it exactly like the tables next to it.

Usage:
    python scripts/derive_incb.py <ucd-dir> [output]
"""

import re
import sys
from pathlib import Path

# `InCB; None` covers the whole codespace as a default and carries no
# information; the three real values are what GB9c is written against.
VALUES = ("Consonant", "Extend", "Linker")

LINE = re.compile(
    r"^([0-9A-Fa-f]{4,6})(?:\.\.([0-9A-Fa-f]{4,6}))?\s*;\s*InCB;\s*(\w+)"
)


def parse(ucd_dir: Path) -> dict[str, list[tuple[int, int]]]:
    src = ucd_dir / "DerivedCoreProperties.txt"
    if not src.is_file():
        sys.exit(f"error: {src} not found")

    found: dict[str, list[tuple[int, int]]] = {v: [] for v in VALUES}
    for line in src.read_text(encoding="utf-8").splitlines():
        line = line.split("#", 1)[0]
        m = LINE.match(line)
        if not m:
            continue
        start_s, end_s, value = m.groups()
        if value not in found:
            continue
        start = int(start_s, 16)
        end = int(end_s, 16) if end_s else start
        found[value].append((start, end))

    for value, ranges in found.items():
        if not ranges:
            sys.exit(f"error: no InCB={value} ranges found in {src}")
        found[value] = merge(ranges)
    return found


def merge(ranges: list[tuple[int, int]]) -> list[tuple[int, int]]:
    """Sort and coalesce adjacent/overlapping ranges, as ucd-generate does."""
    out: list[tuple[int, int]] = []
    for start, end in sorted(ranges):
        if out and start <= out[-1][1] + 1:
            out[-1] = (out[-1][0], max(out[-1][1], end))
        else:
            out.append((start, end))
    return out


def const_name(value: str) -> str:
    return value.upper()


def render(ucd_dir: Path, table: dict[str, list[tuple[int, int]]]) -> str:
    lines = [
        "// DO NOT EDIT THIS FILE. IT WAS AUTOMATICALLY GENERATED BY:",
        "//",
        f"//   scripts/derive_incb.py {ucd_dir}",
        "//",
        "// Indic_Conjunct_Break, derived from DerivedCoreProperties.txt.",
        "",
        "pub const BY_NAME: &'static [(&'static str, &'static [(u32, u32)])] = &[",
        "  " + " ".join(f'("{v}", {const_name(v)}),' for v in VALUES),
        "];",
        "",
    ]
    for value in VALUES:
        lines.append(f"pub const {const_name(value)}: &'static [(u32, u32)] = &[")
        for start, end in table[value]:
            lines.append(f"  ({start}, {end}),")
        lines.append("];")
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    if len(sys.argv) < 2:
        sys.exit(__doc__.strip())
    ucd_dir = Path(sys.argv[1])
    output = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(
        "data/unicode_tables/indic_conjunct_break.rs"
    )
    table = parse(ucd_dir)
    output.write_text(render(ucd_dir, table), encoding="utf-8")
    counts = ", ".join(f"{v}={len(table[v])}" for v in VALUES)
    print(f"Wrote {output} ({counts} ranges)")


if __name__ == "__main__":
    main()
